apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctechfaraz-deploy
spec:
  selector:
    matchLabels:
      app: abctechfaraz_deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: abctechfaraz_deploy
    spec:
     containers:
     - name: abctechfaraz-app
       image: khanfaraz4121/abctechfaraz:latest
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: abctechfaraz-nodeport-svc
spec:
  selector:
    app: abctechfaraz_deploy
  ports:
    - protocol: TCP
      port: 80
      targetport: 8080
  type:Nodeport 